### PR TITLE
Add rule for meta tag

### PR DESCRIPTION
**Pull request by ademyanchuk**
This branch added new functionality. Now all predifined actions can handle not only regular tags, which are in `dataset.dir()`,
but also `file_meta` tags, which are in `dataset.file_meta.dir()`.

This could help user to apply de-identification rule to the meta tags. User is responsible not to break `file_meta` by applying the rules to meta-tags.

### CODE REVIEW

**Comment by finetjul** [comment]
Hi @ademyanchuk ,

Thanks for your work, this seems very promising.

I haven't looked closely yet at your work but I think it would be sad (and not convenient to the community) to keep it as a separate fork. Are you sure you don't you want to merge it ?

**Comment by ademyanchuk** [comment]
Hi @finetjul,
Thank you for the kind words. I thought, there is no active work on this project. 
I was in need for dicom-anonymization and found your project the best fit to start from.
I need it sooner rather than later, so my guess was if there is no active work, I will just develop the fork.
I would love to merge my work and give back to the open source community. Not sure if you find my design decisions  working for you.

I have changed the CLI API and broke backward compatibility. I decided not to give a user the way to provide custom functions and just to stay in the scope of de-id task with "built-in" and tested action functions. I didn't like the idea of customization through the CLI (inconvenient than you have more than 2-3 additional rules) and  my fork master only have now extra-rules through json file. 

I have removed the single file de-id (my fought, it is not common use case) and added de-id for nested collection of folders.
`--type` option in CLI. My master branch README now updated accordingly.

Some minor things are: 
- updated to work with meta-file tags 
- add example of hook on how not to be broke by the real life data than data is inconsistent with dicom standard. Pydicom is strict with standard and one has to fix issues before accessing problematic tags with pydicom `dataset.get` methods. The example is "Exposure" tag, which should have "IS" VR, but in some of my cases  is "DS".
- resolve a minor bug with 4 elements tag tuple
-  started to add unit test to atomic actions functions and have some integration tests in mind for the future.

Not sure, if you would be ok with my breaking changes, although I found those decisions mostly reasonable. 
If you say yes, I would be glad to open PR, and we can try to merge my fork's master into the original project.

Best regards,
Alexey

**Comment by pchoisel** [comment]
Hello @ademyanchuk,

Sorry for the time we took to have a look at your PR and thank you for your work.

I understand your decision to create a new CLI to make the tool recursive, however, I'm not sure why it could not be added as a option in the current CLI. I'm thinking about the `-r` (for recursive) option you can see in a lot of UNIX commands (like `cp`, `mv`, `chmod`, etc...).
Have you considered using the method `walk` from the standard Python module `os.path` to do this recursive treatment ?

Keeping the same CLI would allow us to keep the arguments already implemented.

I'm not sure about the purpose of the `AnonState` class. Is it used to debug ? In any case, I think it should be optional.

Adding a logging system is a great idea, however, I find it a bit intrusive to create a folder in the home folder of the user. My suggestion is : add an new CLI argument allowing the user to specify a path to a log file. If no path is provided, log everything in the stdout (default behavior of the logging module I think.)
What do you think ?

Finally, your code seems to have formatting differences with ours. What formatter are you using and what are its rules ?

Thanks again for your work, I sincerely hope we'll find a way to merge it !
Paul

**Comment by ademyanchuk** [comment]
Hi, Paul @pchoisel 
Thank you for the time invested :)

1. I agree, it is better design to add recursive processing flag to CLI
2. I don't actually see why to use `walk`. It is more generic function and also has to be wrapped to be recursive. I am using standard library `pathlib`. My function `get_dirs` does only one thing - provide a caller with a generator of all directory paths inside the `root_path`. I guess, wrapping `walk` would end up the same thing.
3. I agree on keeping the same CLI. Though, to keep things simple, I would prefer to have only `json file` way of customization.
4. `AnonState` is a wrapper for caching already processed results. It simply saves paths already anonymized. (In case one has a thousand of dicom folders, not to start from scratch when the job quit with some error). I agree, it should be optional.
5. I also agree, it is better to give an option of writing logs and processed state to the user. And by default, log to stdout.
6. I use `black` formatter with default settings (all formatting is provided as pre-commit hooks now in my fork's master).

Summarizing it, my fork's master went quite a bit ahead. I could suggest doing as follows: 
- I will create a branch for merging into original repository
- on this branch I will update as mentioned above, so the CLI still works (mostly) the same way
- will open a new PR to merge this branch into the original repository
- and we will go through, discuss and hopefully merge :)

Tell me what do you think about this?

Also, you can take a look in my current master to see it's current state :)

Best,
Alexey

**Comment by pchoisel** [comment]
Heya, 

Keeping the same CLI will be great.

I got it for `AnonState`. We can keep it when it'll be optional. What do you think about storing the current customization rules in the state, so if they are changed, the state is discarded and the whole root folder is anonymized from start again ?

About the `dicomfields.py` file, it's kind of hard to review it with the format change. Could you add the commit https://github.com/ademyanchuk/dicom-anonymizer/commit/06499dd8032110ef14eafcd7c027a1d7e45fb48a to a .git-blame-ignore-revs file so we can see the real modifications ? (https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame)

I'm not sure about having only the `json file` way of customizing the tool. I think the `-t` and `--dictionary`  command line is still used and does not hurt by being there. Did you plan on using the `-t` parameter for something else ?  

I had a look a your master, adding unit tests is a great idea !

So can you create a new branch and PR ?
Thanks a lot,
Paul

**Comment by ademyanchuk** [comment]
Hi,

Don't have much time, unfortunately. Will try to come back to it somewhat later.

Cheers

**Pull request closed without merging**
