### PR TITLE
Fix anonymization of meta info header + disable check for 4-indices tags

### PR DESCRIPTION
**Pull request by LudvigOlsen**
1) Currently, tags in the meta information header (`0x0002` group) are not applied. This fixes that by applying the action to the `file_meta` dataset instead.

2) In dicomfields.py there are 3 tags made up of 4 ints / hex numbers. `dataset.get()` only works with 2-indices tags, so that lookup always fail (at least for me). This only performs the `get()` call for tags with 1 or 2 indices. I used `<=2` as I believe `get()` accepts a string as well.  See also https://github.com/KitwareMedical/dicom-anonymizer/issues/17

### CODE REVIEW

**Comment by LudvigOlsen** [comment]
Uh, I had missed the private tags part. I guess I should set element to `None` in case `len(tag) > 2` then :)

**Comment by pchoisel** [comment]
Hi @LudvigOlsen,

Thanks for your PR and sorry for the very late answer.
We've patch the issue happening with tags having more than two tags.
However, the other part of your PR (handling of the meta info header) is still relevant.
We could merge it if you removed the second part (only handling tags with 2 or less elements).

Have a great day,
Paul

**Comment by LudvigOlsen** [comment]
Hi @pchoisel ,

I don't currently work with DICOM data, why it's not a priority for me unfortunately.
Feel free to use the parts you like though :)

Best,
Ludvig

**Comment by pchoisel** [comment]
Hi @LudvigOlsen,

Thanks a lot, I will do that.
Have a great day.
Paul

**Comment by pchoisel** [comment]
Closing as this has been fixed in https://github.com/KitwareMedical/dicom-anonymizer/pull/29

**Pull request closed without merging**
